version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  web:
    image: foodtrucks-web
    command: python3 app.py
    depends_on:
      - es
    ports:
      - "5001:5000"
    volumes:
      - ./flask-app:/opt/flask-app

volumes:
    esdata1:
      driver: local
